### ISSUE TITLE
Nome dos municípios

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [assismauro/sismoi#5]
Em todos os serviços onde são retornados os nomes dos Municípios, colocar “/UF” no nome deles, ode UF é a sigla do Estado ao qual eles pertencem, de forma a garantir a unicidade dos nomes.

**Comment by assismauro** [comment]
Foi feito, mas agora tem que mexer na interface, já que, quando se seleciona um recorte por estado, ele mostra o nome do estado em frente ao nome do município, então fica: "Salvador/BA - Bahia"

**Comment by pedro-andrade-inpe** [comment]
@assismauro, quando o recorte for estadual, tem como o servico retornar sem coloca "/UF"? Assim, nao seria necessario alterar a interface grafica.

**Comment by assismauro** [comment]
Uai, até tem, mas eu acho que esse problema é mais da interface. Veja essa tela abaixo. Se eu mudar o serviço, ela vai continuar esquisita com esse troço de Bahia-Bahia:
![image](https://user-images.githubusercontent.com/2077520/56509582-c8360e00-64fd-11e9-80c8-a83c065719b6.png)

**Comment by pedro-andrade-inpe** [comment]
Sim, mas a principio este acima é um problema por si só
